## **BIVARIADOS.**

Este Notebook genera el análisis bivariado tanto por quintiles como por deciles de las variables preliminares seleccionadas.

In [14]:
from ai4b_bigquery import AI4BBigQuery
ai4b_bigquery = AI4BBigQuery('teco-prod-adam-dev-826c')
from utils import calcular_bivariados, exportar_multiples_bivariados_excel

2026-04-15 18:13:32 - INFO - Tiene la ultima version

In [15]:
# Lectura de df
query = '''
--sql
SELECT *
FROM `teco-prod-adam-dev-826c.sdb_datamining.tmp_ppaycapturacreditotecopos_ajustef_train_preabt_DG`
'''

df = ai4b_bigquery.run_job_batch(script=query).to_dataframe()
df.head(1)

c:\Users\u634943\OneDrive - Telecom Argentina SA\Documentos\FACTORYABT\fabt_venv\Lib\site-packages\google\cloud\bigquery\table.py:2086: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

,cuil_cuit,periodo,target,max_edad_m0,max_sco_ser_m0,max_antiguedad_key_m0,sum_fact_imp_u3m,max_q_pag_efe_u6m,sum_count_sit_1_m0,sum_count_sit_1_u3m,...,avg_gaming_nivel_u6m_perc,avg_billeteras_virtuales_nivel_u6m_perc,max_billeteras_virtuales_nivel_u3m_perc,avg_bancos_nivel_u6m_perc,max_bancos_nivel_u3m_perc,max_promociones_movil_encurso_meses_bonificados_u3m_perc,sum_recarga_u6m_perc,sum_SALDO_u3m_perc,sum_DOWNLINK_MB_m0_perc,sum_MBPS_u3m_perc
0,23131987889,202501,0,67.0,993.0,9457.0,13474.35,2.0,0.0,0.0,...,percentil_25,percentil_75,percentil_66,percentil_75,percentil_75,percentil_33,cero_o_menos,percentil_66,percentil_25,percentil_50

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25310 entries, 0 to 25309
Data columns (total 69 columns):
 #   Column                                                    Non-Null Count  Dtype
---  ------                                                    --------------  -----
 0   cuil_cuit                                                 25310 non-null  Int64
 1   periodo                                                   25310 non-null  Int64
 2   target                                                    25310 non-null  Int64
 3   max_edad_m0                                               25310 non-null  float64
 4   max_sco_ser_m0                                            25310 non-null  float64
 5   max_antiguedad_key_m0                                     25310 non-null  float64
 6   sum_fact_imp_u3m                                          25310 non-null  float64
 7   max_q_pag_efe_u6m                                         25310 non-null  float64
 8   sum_count_sit_1_m0                                        25310 non-null  float64
 9   sum_count_sit_1_u3m                                       25310 non-null  float64
 10  sum_monto_m0_vs_u6m                                       25310 non-null  float64
 11  sum_monto_bench_u3m_vs_u6m                                25310 non-null  float64
 12  sum_monto_bench_m0                                        25310 non-null  float64
 13  sum_monto_bancaria_u3m_vs_u6m                             25310 non-null  float64
 14  sum_monto_bancaria_m0                                     25310 non-null  float64
 15  max_tax_amt_movil_u6m                                     25310 non-null  float64
 16  sum_tax_amt_movil_u6m                                     25310 non-null  float64
 17  max_porc_descuento_u6m                                    25310 non-null  float64
 18  sum_recargas_sos_u6m                                      25310 non-null  float64
 19  max_cant_cons_12m_m0                                      25310 non-null  float64
 20  max_sco_ser_12m_m0_vs_u6m                                 25310 non-null  float64
 21  max_lc_monto_u6m                                          25310 non-null  float64
 22  max_saldo_prestamos_per_otr_m0_vs_u6m                     25310 non-null  float64
 23  sum_debit_amount_u6m_vs_sum_count_debit_amount_u6m        25310 non-null  float64
 24  max_debit_amount_m0                                       25310 non-null  float64
 25  min_debit_amount_u3m                                      25310 non-null  float64
 26  avg_transporte_nivel_u6m                                  25310 non-null  float64
 27  avg_gaming_nivel_u6m                                      25310 non-null  float64
 28  avg_billeteras_virtuales_nivel_u6m                        25310 non-null  float64
 29  max_billeteras_virtuales_nivel_u3m                        25310 non-null  float64
 30  avg_bancos_nivel_u6m                                      25310 non-null  float64
 31  max_bancos_nivel_u3m                                      25310 non-null  float64
 32  max_promociones_movil_encurso_meses_bonificados_u3m       25310 non-null  float64
 33  sum_recarga_u6m                                           25310 non-null  float64
 34  sum_SALDO_u3m                                             25310 non-null  float64
 35  sum_DOWNLINK_MB_m0                                        25310 non-null  float64
 36  sum_MBPS_u3m                                              25310 non-null  float64
 37  max_antiguedad_key_m0_perc                                25310 non-null  object
 38  sum_fact_imp_u3m_perc                                     25310 non-null  object
 39  max_q_pag_efe_u6m_perc                                    25310 non-null  object
 40  sum_count_sit_1_m0_perc                                   25310 non-null  object
 41  sum_count_sit_1_u3m_perc                                  25310 non-null  object
 42  sum_monto_m0_vs_u6m_perc                                  25310 non-null  object
 43  sum_monto_bench_u3m_vs_u6m_perc                           25310 non-null  object
 44  sum_monto_bench_m0_perc                                   25310 non-null  object
 45  sum_monto_bancaria_u3m_vs_u6m_perc                        25310 non-null  object
 46  sum_monto_bancaria_m0_perc                                25310 non-null  object
 47  max_tax_amt_movil_u6m_perc                                25310 non-null  object
 48  sum_tax_amt_movil_u6m_perc                                25310 non-null  object
 49  max_porc_descuento_u6m_perc                               25310 non-null  object
 50  sum_recargas_sos_u6m_perc                                 25310 non-null  object
 51  max_cant_cons_12m_m0_perc                                 25310 non-null  object
 52  max_sco_ser_12m_m0_vs_u6m_perc                            25310 non-null  object
 53  max_lc_monto_u6m_perc                                     25310 non-null  object
 54  max_saldo_prestamos_per_otr_m0_vs_u6m_perc                25310 non-null  object
 55  sum_debit_amount_u6m_vs_sum_count_debit_amount_u6m_perc   25310 non-null  object
 56  max_debit_amount_m0_perc                                  25310 non-null  object
 57  min_debit_amount_u3m_perc                                 25310 non-null  object
 58  avg_transporte_nivel_u6m_perc                             25310 non-null  object
 59  avg_gaming_nivel_u6m_perc                                 25310 non-null  object
 60  avg_billeteras_virtuales_nivel_u6m_perc                   25310 non-null  object
 61  max_billeteras_virtuales_nivel_u3m_perc                   25310 non-null  object
 62  avg_bancos_nivel_u6m_perc                                 25310 non-null  object
 63  max_bancos_nivel_u3m_perc                                 25310 non-null  object
 64  max_promociones_movil_encurso_meses_bonificados_u3m_perc  25310 non-null  object
 65  sum_recarga_u6m_perc                                      25310 non-null  object
 66  sum_SALDO_u3m_perc                                        25310 non-null  object
 67  sum_DOWNLINK_MB_m0_perc                                   25310 non-null  object
 68  sum_MBPS_u3m_perc                                         25310 non-null  object
dtypes: Int64(3), float64(34), object(32)
memory usage: 13.4+ MB

In [17]:
df_biv_q = calcular_bivariados(
    df=df,
    target_col='target',
    n_bins=5,
    metodo='quantile',
    excluir_cols=['cuil_cuit', 'periodo']
    # forzar_categoricas=['tpv_tendencia_m0_vs_m_1', 'sp_tendencia_m0_vs_m_1']
)
df_biv_q.head(1)

,variable,bin,minimo,maximo,cantidad,cantmalos,cantbuenos,porcmalogrupo,porctotal,porcbuenostotal,porcmalostotal,woe,iv,iv_total_variable
0,max_edad_m0,1,18.0,35.0,5423,1370,4053,25.26,21.43,17.79,54.13,-1.112752,40.437408,105.113757

In [18]:
df_biv_d = calcular_bivariados(
    df=df,
    target_col='target',
    n_bins=10,
    metodo='quantile',
    excluir_cols=['cuil_cuit', 'periodo']
    # forzar_categoricas=['tpv_tendencia_m0_vs_m_1', 'sp_tendencia_m0_vs_m_1']
)
df_biv_d.head(1)

,variable,bin,minimo,maximo,cantidad,cantmalos,cantbuenos,porcmalogrupo,porctotal,porcbuenostotal,porcmalostotal,woe,iv,iv_total_variable
0,max_edad_m0,1,18.0,29.0,2566,760,1806,29.62,10.14,7.93,30.03,-1.331544,29.427122,113.601317

In [19]:
exportar_multiples_bivariados_excel(
    hojas={
        'Quintiles': df_biv_q,
        'Deciles': df_biv_d
    },
    archivo_salida=r"C:\Users\u634943\Downloads\ppaycapturacreditotecopos_bivariado_ajustef_3.xlsx",
    columnas_color=['porcmalogrupo']
)

  ✓ Hoja 'Quintiles': 237 filas de datos
  ✓ Hoja 'Deciles': 347 filas de datos

✓ Excel exportado a: C:\Users\u634943\Downloads\ppaycapturacreditotecopos_bivariado_ajustef_3.xlsx
  - Hojas: ['Quintiles', 'Deciles']
  - Columnas con formato condicional: ['porcmalogrupo']